### ISSUE TITLE
Creare la pagina relativa alle info del laboratorio del dib

### ISSUE THREAD

**Issue by BarbieriGiuseppe** [BarbieriGiuseppe/GRUPPO_LCB#1]
creare all'interno della cartella infolaboratori le pagine relative ai laboratori convenzionati e svilupparle.

**Comment by LorussoDanilo** [comment]
Aggiornamenti nella commit: 82a0eac 
Pagina dedicata al laboratorio DIB quasi terminata

**Comment by LorussoDanilo** [comment]
Il logo non è visualizzabile
